language: python

python:
  - "2.7"
  
install:
  - "pip install lxml"

script:
  -  cd python
  -  python CheckModelDB.py
  -  python activity.py 10
  -  python curate.py 10
  -  python retrieveNML2.py 20
