language: python

python:
  - "2.6"
  - "2.7"
  - "3.5" 
  
install:
  - pip install libNeuroML
  - cd python
  - pip install .
script:
  -  cd examples
  -  if [[ $TRAVIS_PYTHON_VERSION -ne "3.5" ]]; then ./quicktest.sh -a; else ./quicktest.sh ; fi

