language: python

python:
  - "2.7"
  
install:
  - "pip install lxml"
  - "git clone https://github.com/NeuralEnsemble/libNeuroML.git"
  - "cd libNeuroML"
  - "git checkout development"
  - "sudo python setup.py install" 
  - "cd .."
script:
  -  cd python
  -  ./quicktest.sh
